dotfiles_dir = ".dotfiles"
  
[settings]
# Una matriz de rutas de archivos toml que contienen las variables
# para inyectar en sus archivos de puntos con plantilla.

# Puede tener varios archivos var siempre que los nombres de
# las variables no colisionen.
# vars = [ "vars.toml" ]

# Una matriz de comandos de shell posteriores a la instalación
# posthooks = [ "sway reloadh" ]

[settings.dots]

# Una entrada de punto que representa un enlace simbólico,
# `source` es relativa a `dotfiles_dir` y `target` serán
# relativos al directorio $HOME o absolutos.

nvim = { source = "nvim", target = ".config/nvim" }
zsh = { source = "zsh/.zshrc", target = ".zshrc" }
