[symlinks]
"nvim/.dotter/cache.toml" = "/home/kevst/.config/nvim/.dotter/cache.toml"
"nvim/.dotter/global.toml" = "/home/kevst/.config/nvim/.dotter/global.toml"
"nvim/.dotter/local.toml" = "/home/kevst/.config/nvim/.dotter/local.toml"
"nvim/.editorconfig" = "/home/kevst/.config/nvim/.editorconfig"
"nvim/.luacheckrc" = "/home/kevst/.config/nvim/.luacheckrc"
"nvim/.luarc.json" = "/home/kevst/.config/nvim/.luarc.json"
"nvim/.stylua.toml" = "/home/kevst/.config/nvim/.stylua.toml"
"nvim/init.lua" = "/home/kevst/.config/nvim/init.lua"
"nvim/justfile" = "/home/kevst/.config/nvim/justfile"
"nvim/lua/config/completition/init.lua" = "/home/kevst/.config/nvim/lua/config/completition/init.lua"
"nvim/lua/config/icons.lua" = "/home/kevst/.config/nvim/lua/config/icons.lua"
"nvim/lua/config/init.lua" = "/home/kevst/.config/nvim/lua/config/init.lua"
"nvim/lua/config/keymaps.lua" = "/home/kevst/.config/nvim/lua/config/keymaps.lua"
"nvim/lua/config/lazy.lua" = "/home/kevst/.config/nvim/lua/config/lazy.lua"
"nvim/lua/config/lsp/attach.lua" = "/home/kevst/.config/nvim/lua/config/lsp/attach.lua"
"nvim/lua/config/lsp/init.lua" = "/home/kevst/.config/nvim/lua/config/lsp/init.lua"
"nvim/lua/config/lsp/mason.lua" = "/home/kevst/.config/nvim/lua/config/lsp/mason.lua"
"nvim/lua/config/lsp/servers.lua" = "/home/kevst/.config/nvim/lua/config/lsp/servers.lua"
"nvim/lua/config/lsp/setups.lua" = "/home/kevst/.config/nvim/lua/config/lsp/setups.lua"
"nvim/lua/config/options.lua" = "/home/kevst/.config/nvim/lua/config/options.lua"
"nvim/lua/plugins/autopairs.lua" = "/home/kevst/.config/nvim/lua/plugins/autopairs.lua"
"nvim/lua/plugins/codeium.lua" = "/home/kevst/.config/nvim/lua/plugins/codeium.lua"
"nvim/lua/plugins/colorscheme.lua" = "/home/kevst/.config/nvim/lua/plugins/colorscheme.lua"
"nvim/lua/plugins/completition.lua" = "/home/kevst/.config/nvim/lua/plugins/completition.lua"
"nvim/lua/plugins/dashboard/init.lua" = "/home/kevst/.config/nvim/lua/plugins/dashboard/init.lua"
"nvim/lua/plugins/dashboard/logo.lua" = "/home/kevst/.config/nvim/lua/plugins/dashboard/logo.lua"
"nvim/lua/plugins/gitsigns.lua" = "/home/kevst/.config/nvim/lua/plugins/gitsigns.lua"
"nvim/lua/plugins/init.lua" = "/home/kevst/.config/nvim/lua/plugins/init.lua"
"nvim/lua/plugins/lsp.lua" = "/home/kevst/.config/nvim/lua/plugins/lsp.lua"
"nvim/lua/plugins/lualine.lua" = "/home/kevst/.config/nvim/lua/plugins/lualine.lua"
"nvim/lua/plugins/neo-tree.lua" = "/home/kevst/.config/nvim/lua/plugins/neo-tree.lua"
"nvim/lua/plugins/notifications.lua" = "/home/kevst/.config/nvim/lua/plugins/notifications.lua"
"nvim/lua/plugins/oil.lua" = "/home/kevst/.config/nvim/lua/plugins/oil.lua"
"nvim/lua/plugins/syntax.lua" = "/home/kevst/.config/nvim/lua/plugins/syntax.lua"
"nvim/lua/plugins/telescope.lua" = "/home/kevst/.config/nvim/lua/plugins/telescope.lua"
"nvim/lua/plugins/treesitter.lua" = "/home/kevst/.config/nvim/lua/plugins/treesitter.lua"
"zsh/zshrc.sh" = "/home/kevst/.zshrc"

[templates]
