# Muestra la lista de comandos disponibles
default:
    @just --list

# Comprobar calidad del codigo
check:
  prettier --check --write .
  shellcheck -x --shell=bash  zshrc.sh
  find src/ -type f -name "*.sh" -exec shellcheck -x --shell=bash {} +
